version: '3.4'

services:
  server:
    image: server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
  mongodb-Cont:
    image: mongo:latest //defining Docker image
    container_name: mongoDB-Cont
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_cont:/data/db
  
  volumes:
    mongodb_data_cont:
