service:
    name: harness_calendar_bookings_server
    identifier: calendar-bookings-server
    serviceDefinition:
        type: Kubernetes
        spec:
            manifests:
                - manifest:
                    identifier: calendar-bookings-server
                    type: K8sManifest
                    spec:
                      store:
                        type: Github
                        spec:
                            connectorRef: harnessgitconnector
                            gitFetchType: Branch
                            paths:
                                - calendar-bookings-server-deployment.yaml
                                - calendar-bookings-server-svc.yaml
                            branch: master
                        skipResourceVersioning: false
                        enableDeclarativeRollback: false
    gitOpsEnabled: false